services:
  - type: web
    name: chatmit-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_DB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
